const META_DATA_CHANNEL_LABEL = 'metaDataChannel';
const MAXIMUM_MESSAGE_SIZE = 16384;
const END_OF_FILE_MESSAGE = 'EOF';

export { META_DATA_CHANNEL_LABEL, MAXIMUM_MESSAGE_SIZE, END_OF_FILE_MESSAGE };
